[package]
name = "subtract-fileset"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
generic-array = "0.14.7"
sha2 = { version = "0.10.8", features = ["asm"] }
walkdir = "2.5.0"
